version: "3"

volumes:
  mysql_data:
  wordpress_data:

networks:
  wordpress_network:
    driver: bridge
services:
    db:
      image: mysql:9.4
      container_name: mysql-container
      restart: always
      environment:
        MYSQL_USER: g2_wordpress
        MYSQL_PASSWORD: gaurav123
        MYSQL_ROOT_PASSWORD: rootbaba
        MYSQL_DATABASE: wordpress_db
      volumes:
        - mysql_data:/var/lib/mysql
      networks:
        - wordpress_network
      ports:
        - 3306:3306

        
    wordpress:
      depends_on: 
        - db
      image: wordpress:latest
      container_name: wordpress-container
      restart: always
      environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: g2_wordpress
        WORDPRESS_DB_PASSWORD: gaurav123
      volumes:
        - wordpress_data:/var/www/html
      networks:
        - wordpress_network

      
          
  